DROP TABLE ODONTOLOGOS IF EXISTS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMERO_MATRICULA VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '156', 'Luisa', 'Vargas'),
(DEFAULT, '457', 'ARYA', 'LOPEZ');